# General UI strings
plugin.name=CodeAuditAssistant
plugin.description=This plugin is a code audit assistant tool that helps you quickly locate sink points in your project and find call paths.

# Plugin description
plugin.description.detail=This plugin is a code audit assistant tool that helps you quickly locate sink points in your project and find call paths.\n\nThe plugin works by building graphs based on PSI and finding method call chains through call relationships in the graph.\n\nThe plugin consists of two parts: CodeAuditAssistant and SinkFinder.

# Tool Windows
toolwindow.codeauditassistant=CodeAuditAssistant

# Actions
action.buildcallgraph=Build Call Graph
action.searchassink=Search As Sink

# UI Components
ui.email=Email
ui.github=GitHub

# Tabs
tab.decompiler=Decompiler
tab.code.analysis=Code Analysis
tab.sink.finder=Sink Finder

# Errors

# CallGraph Panel
callgraph.loaded=Loaded CallGraph from persistent state.
callgraph.not.found=No existing CallGraph found.
callgraph.generate.button=Generate CallGraph
callgraph.search.results=Search Results
callgraph.search.button=Search
callgraph.find.method.button=Find Method
callgraph.contains.info=Info
callgraph.contains.path=Path
callgraph.class.name=Class Name:
callgraph.access.modifier=Access Modifier:
callgraph.method.modifier=Method Modifier:
callgraph.method.name=Method Name:
callgraph.param.count=Param Count:
callgraph.param.type=Param Type:
callgraph.param.name=Param Name:
callgraph.varargs=Varargs:
callgraph.throws.clause=Throws Clause:
callgraph.return.type=Return Type:
callgraph.annotations=Annotations:

# Status Panel
status.system.platform=System Plat: {0}
status.callgraph.not.ready=CallGraph: Not ready
status.callgraph.ready=CallGraph: Ready
status.method.count=MethodNode: {0}
status.memory.usage=Used memory: {0} MB
status.build.info.none=Build info: No info
status.build.info=Build info: {0}
status.search.info.none=Search info: No info
status.search.info=Search info: {0}
status.error.none=Error: No errors
status.error=Error: {0}

# Search Panel
search.label.root=ROOT:
search.label.sink=SINK:

# Panel Titles
panel.title.root.methods=Root Methods
panel.title.info=Info
panel.title.search.results=Search Results

# Buttons
button.toggle.panel=Toggle Panel

# Decompiler Panel
decompiler.run.button=Run
decompiler.execute.failed=Execute task failed: {0}

# Sink Finder Tab
sink.table.column.file=File
sink.table.column.line=Line
sink.table.column.sink.class=SinkClass
sink.table.column.sink.method=SinkMethod
sink.table.column.type=Type
sink.table.column.subtype=SubType
sink.table.column.call.mode=CallMode
sink.button.init=Init Sink
sink.progress.finding=Finding sink method
sink.tab.id=Issue Problems Tab
sink.tree.root=Issue Categories 
