name: Gradle Build Plugin

on:
  push:
    branches:
      - preview
  pull_request:
    branches:
      - preview

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: SecurityInspector
          path: ./build/libs/
          compression-level: 0

