name: Gradle Plugin Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Plugin with Gradle
        run: ./gradlew buildPlugin

      - name: Generate Release Notes
        id: generate_notes
        uses: actions/generate-release-notes@v2
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          tag_name: ${{ github.event.release.tag_name }}

      - name: Update Release with Notes
        uses: actions/github-script@v6
        with:
          script: |
            const { data: release } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.payload.release.tag_name,
            });
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              body: `${{ steps.generate_notes.outputs.notes }}`,
            });

      - name: Upload Plugin to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/libs/SecurityInspector-${{ github.event.release.tag_name }}.jar
          asset_name: SecurityInspector-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive
