name: Gradle Plugin Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The release tag to upload the JAR to'
        required: true
        default: 'Preview-v1.0'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build Plugin with Gradle
      run: ./gradlew buildPlugin

    - name: Upload Plugin to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/SpringKill-team/SecurityInspector/releases/181666135/assets?name=SecurityInspector-Preview-v1.0.jar
        asset_path: ./build/libs/SecurityInspector-${{ github.event.inputs.release_tag }}.jar
        asset_name: SecurityInspector-${{ github.event.inputs.release_tag }}.jar
        asset_content_type: application/java-archive
